import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "LumTerior",
  description: "Generated by 고려대학교 SW 지능정보 아카데미 2조 (안지홍, 유지혜, 이승재, 이정현, 하동우, 홍규린)",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
